export default [
  {
    id: 1,
    year: 2024,
    draw: 'Opening',
    round: 'First Round',
    round_number: 1,
    player1_id: 1,
    player2_id: 2,
    winner_id: 1,
    loser_id: 2,
    score: '6-3 6-2',
  },
  {
    id: 2,
    year: 2024,
    draw: 'Opening',
    round: 'First Round',
    round_number: 2,
    player1_id: 3,
    player2_id: 4,
    winner_id: 3,
    loser_id: 4,
    score: '6-3 6-2',
  },
  {
    id: 3,
    year: 2024,
    draw: 'Opening',
    round: 'First Round',
    round_number: 3,
    player1_id: 5,
    player2_id: 6,
    winner_id: 5,
    loser_id: 6,
    score: '6-3 6-2',
  },
  {
    id: 4,
    year: 2024,
    draw: 'Opening',
    round: 'First Round',
    round_number: 4,
    player1_id: 7,
    player2_id: 8,
    winner_id: 7,
    loser_id: 8,
    score: '6-3 6-2',
  },
  {
    id: 5,
    year: 2024,
    draw: 'Plate',
    round: 'Semi Final',
    round_number: 1,
    player1_id: 10,
    player2_id: 5,
    winner_id: 5,
    loser_id: 10,
    score: '6-3 6-2',
  },
  {
    id: 6,
    year: 2024,
    draw: 'Plate',
    round: 'Semi Final',
    round_number: 2,
    player1_id: 3,
    player2_id: 9,
    winner_id: 9,
    loser_id: 3,
    score: '6-3 6-2',
  },
  {
    id: 7,
    year: 2024,
    draw: 'Plate',
    round: 'Play off',
    round_number: 1,
    player1_id: 1,
    player2_id: 2,
    winner_id: 1,
    loser_id: 2,
    score: '6-3 6-2',
  },
  {
    id: 8,
    year: 2024,
    draw: 'Plate',
    round: 'Final',
    round_number: 2,
    player1_id: 3,
    player2_id: 4,
    winner_id: 3,
    loser_id: 4,
    score: '6-3 6-2',
  },
  {
    id: 9,
    year: 2024,
    draw: 'Main',
    round: 'Semi Final',
    round_number: 3,
    player1_id: 5,
    player2_id: 6,
    winner_id: 5,
    loser_id: 6,
    score: '6-3 6-2',
  },
  {
    id: 10,
    year: 2024,
    draw: 'Main',
    round: 'Semi Final',
    round_number: 1,
    player1_id: 9,
    player2_id: 1,
    winner_id: 1,
    loser_id: 9,
    score: '6-3 6-2',
  },
  {
    id: 11,
    year: 2024,
    draw: 'Main',
    round: 'Play off',
    round_number: 1,
    player1_id: 2,
    player2_id: 3,
    winner_id: 2,
    loser_id: 3,
    score: '6-3 6-2',
  },
  {
    id: 12,
    year: 2024,
    draw: 'Main',
    round: 'Final',
    round_number: 1,
    player1_id: 5,
    player2_id: 7,
    winner_id: 7,
    loser_id: 5,
    score: '6-3 6-2',
  },
  {
    id: 13,
    year: 2025,
    draw: 'Opening',
    round: 'First Round',
    round_number: 1,
    player1_id: 1,
    player2_id: 2,
    winner_id: 1,
    loser_id: 2,
    score: '6-3 6-2',
  },
  {
    id: 14,
    year: 2025,
    draw: 'Opening',
    round: 'First Round',
    round_number: 2,
    player1_id: 3,
    player2_id: 4,
    winner_id: 3,
    loser_id: 4,
    score: '6-3 6-2',
  },
  {
    id: 15,
    year: 2025,
    draw: 'Opening',
    round: 'First Round',
    round_number: 3,
    player1_id: 5,
    player2_id: 6,
    winner_id: 5,
    loser_id: 6,
    score: '6-3 6-2',
  },
  {
    id: 16,
    year: 2025,
    draw: 'Opening',
    round: 'First Round',
    round_number: 4,
    player1_id: 7,
    player2_id: 8,
    winner_id: 7,
    loser_id: 8,
    score: '6-3 6-2',
  },
  {
    id: 17,
    year: 2025,
    draw: 'Plate',
    round: 'Semi Final',
    round_number: 1,
    player1_id: 10,
    player2_id: 5,
    winner_id: 5,
    loser_id: 10,
    score: '6-3 6-2',
  },
  {
    id: 18,
    year: 2025,
    draw: 'Plate',
    round: 'Semi Final',
    round_number: 2,
    player1_id: 3,
    player2_id: 9,
    winner_id: 9,
    loser_id: 3,
    score: '6-3 6-2',
  },
  {
    id: 19,
    year: 2025,
    draw: 'Plate',
    round: 'Play off',
    round_number: 1,
    player1_id: 1,
    player2_id: 2,
    winner_id: 1,
    loser_id: 2,
    score: '6-3 6-2',
  },
  {
    id: 20,
    year: 2025,
    draw: 'Plate',
    round: 'Final',
    round_number: 2,
    player1_id: 3,
    player2_id: 4,
    winner_id: 3,
    loser_id: 4,
    score: '6-3 6-2',
  },
  {
    id: 21,
    year: 2025,
    draw: 'Main',
    round: 'Semi Final',
    round_number: 3,
    player1_id: 5,
    player2_id: 6,
    winner_id: 5,
    loser_id: 6,
    score: '6-3 6-2',
  },
  {
    id: 22,
    year: 2025,
    draw: 'Main',
    round: 'Semi Final',
    round_number: 1,
    player1_id: 9,
    player2_id: 1,
    winner_id: 1,
    loser_id: 9,
    score: '6-3 6-2',
  },
  {
    id: 23,
    year: 2025,
    draw: 'Main',
    round: 'Play off',
    round_number: 1,
    player1_id: 2,
    player2_id: 3,
    winner_id: 2,
    loser_id: 3,
    score: '6-3 6-2',
  },
  {
    id: 24,
    year: 2025,
    draw: 'Main',
    round: 'Final',
    round_number: 1,
    player1_id: 5,
    player2_id: 7,
    winner_id: 7,
    loser_id: 5,
    score: '6-3 6-2',
  },
  {
    id: 25,
    year: 2026,
    draw: 'Opening',
    round: 'First Round',
    round_number: 1,
    player1_id: 1,
    player2_id: 2,
    winner_id: 1,
    loser_id: 2,
    score: '6-3 6-2',
  },
  {
    id: 26,
    year: 2026,
    draw: 'Opening',
    round: 'First Round',
    round_number: 2,
    player1_id: 3,
    player2_id: 4,
    winner_id: 3,
    loser_id: 4,
    score: '6-3 6-2',
  },
  {
    id: 27,
    year: 2026,
    draw: 'Opening',
    round: 'First Round',
    round_number: 3,
    player1_id: 5,
    player2_id: 6,
    winner_id: 5,
    loser_id: 6,
    score: '6-3 6-2',
  },
  {
    id: 28,
    year: 2026,
    draw: 'Opening',
    round: 'First Round',
    round_number: 4,
    player1_id: 7,
    player2_id: 8,
    winner_id: 7,
    loser_id: 8,
    score: '6-3 6-2',
  },
  {
    id: 29,
    year: 2026,
    draw: 'Plate',
    round: 'Semi Final',
    round_number: 1,
    player1_id: 10,
    player2_id: 5,
    winner_id: 5,
    loser_id: 10,
    score: '6-3 6-2',
  },
  {
    id: 30,
    year: 2026,
    draw: 'Plate',
    round: 'Semi Final',
    round_number: 2,
    player1_id: 3,
    player2_id: 9,
    winner_id: 9,
    loser_id: 3,
    score: '6-3 6-2',
  },
  {
    id: 31,
    year: 2026,
    draw: 'Plate',
    round: 'Play off',
    round_number: 1,
    player1_id: 1,
    player2_id: 2,
    winner_id: 1,
    loser_id: 2,
    score: '6-3 6-2',
  },
  {
    id: 32,
    year: 2026,
    draw: 'Plate',
    round: 'Final',
    round_number: 2,
    player1_id: 3,
    player2_id: 4,
    winner_id: 3,
    loser_id: 4,
    score: '6-3 6-2',
  },
  {
    id: 33,
    year: 2026,
    draw: 'Main',
    round: 'Semi Final',
    round_number: 3,
    player1_id: 5,
    player2_id: 6,
    winner_id: 5,
    loser_id: 6,
    score: '6-3 6-2',
  },
  {
    id: 34,
    year: 2026,
    draw: 'Main',
    round: 'Semi Final',
    round_number: 1,
    player1_id: 9,
    player2_id: 1,
    winner_id: 1,
    loser_id: 9,
    score: '6-3 6-2',
  },
  {
    id: 35,
    year: 2026,
    draw: 'Main',
    round: 'Play off',
    round_number: 1,
    player1_id: 2,
    player2_id: 3,
    winner_id: 2,
    loser_id: 3,
    score: '6-3 6-2',
  },
  {
    id: 36,
    year: 2026,
    draw: 'Main',
    round: 'Final',
    round_number: 1,
    player1_id: 5,
    player2_id: 7,
    winner_id: 7,
    loser_id: 5,
    score: '6-3 6-2',
  },
  {
    id: 37,
    year: 2027,
    draw: 'Opening',
    round: 'First Round',
    round_number: 1,
    player1_id: 1,
    player2_id: 2,
    winner_id: 1,
    loser_id: 2,
    score: '6-3 6-2',
  },
  {
    id: 38,
    year: 2027,
    draw: 'Opening',
    round: 'First Round',
    round_number: 2,
    player1_id: 3,
    player2_id: 4,
    winner_id: 3,
    loser_id: 4,
    score: '6-3 6-2',
  },
  {
    id: 39,
    year: 2027,
    draw: 'Opening',
    round: 'First Round',
    round_number: 3,
    player1_id: 5,
    player2_id: 6,
    winner_id: 5,
    loser_id: 6,
    score: '6-3 6-2',
  },
  {
    id: 40,
    year: 2027,
    draw: 'Opening',
    round: 'First Round',
    round_number: 4,
    player1_id: 7,
    player2_id: 8,
    winner_id: 7,
    loser_id: 8,
    score: '6-3 6-2',
  },
  {
    id: 41,
    year: 2027,
    draw: 'Plate',
    round: 'Semi Final',
    round_number: 1,
    player1_id: 10,
    player2_id: 5,
    winner_id: 5,
    loser_id: 10,
    score: '6-3 6-2',
  },
  {
    id: 42,
    year: 2027,
    draw: 'Plate',
    round: 'Semi Final',
    round_number: 2,
    player1_id: 3,
    player2_id: 9,
    winner_id: 9,
    loser_id: 3,
    score: '6-3 6-2',
  },
  {
    id: 43,
    year: 2027,
    draw: 'Plate',
    round: 'Play off',
    round_number: 1,
    player1_id: 1,
    player2_id: 2,
    winner_id: 1,
    loser_id: 2,
    score: '6-3 6-2',
  },
  {
    id: 44,
    year: 2027,
    draw: 'Plate',
    round: 'Final',
    round_number: 2,
    player1_id: 3,
    player2_id: 4,
    winner_id: 3,
    loser_id: 4,
    score: '6-3 6-2',
  },
  {
    id: 45,
    year: 2027,
    draw: 'Main',
    round: 'Semi Final',
    round_number: 3,
    player1_id: 5,
    player2_id: 6,
    winner_id: 5,
    loser_id: 6,
    score: '6-3 6-2',
  },
  {
    id: 46,
    year: 2027,
    draw: 'Main',
    round: 'Semi Final',
    round_number: 1,
    player1_id: 9,
    player2_id: 1,
    winner_id: 1,
    loser_id: 9,
    score: '6-3 6-2',
  },
  {
    id: 47,
    year: 2027,
    draw: 'Main',
    round: 'Play off',
    round_number: 1,
    player1_id: 2,
    player2_id: 3,
    winner_id: 2,
    loser_id: 3,
    score: '6-3 6-2',
  },
  {
    id: 48,
    year: 2027,
    draw: 'Main',
    round: 'Final',
    round_number: 1,
    player1_id: 5,
    player2_id: 7,
    winner_id: 7,
    loser_id: 5,
    score: '6-3 6-2',
  },
];
