export default [
  {
    id: 1,
    score: '6-3 6-2',
    winner_id: 1,
    loser_id: 2,
    draw: 'opening',
    round: 'first round',
    round_number: 1,
    year: 2024,
    created_at: null,
  },
  {
    id: 2,
    score: '6-3 6-2',
    winner_id: 3,
    loser_id: 4,
    draw: 'opening',
    round: 'first round',
    round_number: 2,
    year: 2024,
    created_at: null,
  },
  {
    id: 3,
    score: '6-3 6-2',
    winner_id: 5,
    loser_id: 6,
    draw: 'opening',
    round: 'first round',
    round_number: 3,
    year: 2024,
    created_at: null,
  },
  {
    id: 4,
    score: '6-3 6-2',
    winner_id: 7,
    loser_id: 8,
    draw: 'opening',
    round: 'first round',
    round_number: 4,
    year: 2024,
    created_at: null,
  },
  {
    id: 5,
    score: '6-4 6-4',
    winner_id: 4,
    loser_id: 2,
    draw: 'plate',
    round: 'semi final',
    round_number: 1,
    year: 2024,
    created_at: null,
  },
  {
    id: 6,
    score: '7-5 6-3',
    winner_id: 7,
    loser_id: 6,
    draw: 'plate',
    round: 'semi final',
    round_number: 2,
    year: 2024,
    created_at: null,
  },
  {
    id: 7,
    score: '6-2 7-5',
    winner_id: 2,
    loser_id: 6,
    draw: 'plate',
    round: 'playoff',
    round_number: 1,
    year: 2024,
    created_at: null,
  },
  {
    id: 8,
    score: '7-6 (7-5) 7-6 (7-3)',
    winner_id: 7,
    loser_id: 4,
    draw: 'plate',
    round: 'final',
    round_number: 1,
    year: 2024,
    created_at: null,
  },
  {
    id: 9,
    score: '6-1 6-4',
    winner_id: 1,
    loser_id: 3,
    draw: 'main',
    round: 'semi final',
    round_number: 1,
    year: 2024,
    created_at: null,
  },
  {
    id: 10,
    score: '6-2 6-2',
    winner_id: 8,
    loser_id: 5,
    draw: 'main',
    round: 'semi final',
    round_number: 2,
    year: 2024,
    created_at: null,
  },
  {
    id: 11,
    score: '6-2 6-7 (5-7) 6-1',
    winner_id: 3,
    loser_id: 5,
    draw: 'main',
    round: 'playoff',
    round_number: 1,
    year: 2024,
    created_at: null,
  },
  {
    id: 12,
    score: '0-6 6-3 6-4',
    winner_id: 1,
    loser_id: 8,
    draw: 'main',
    round: 'final',
    round_number: 1,
    year: 2024,
    created_at: null,
  },
];
